version: "3.9"

services:
  db:
    image: postgres:15
    container_name: homeiq-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: homeiq
      POSTGRES_PASSWORD: homeiqpassword
      POSTGRES_DB: homeiq
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: homeiq-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://homeiq:homeiqpassword@db:5432/homeiq
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  db_data:
