services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - PORT=3001
    env_file:
      - ./backend/.env
    command: node dist/index.js

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: homeiq
      POSTGRES_PASSWORD: homeiqpassword
      POSTGRES_DB: homeiq
    ports:
      - "5432:5432"
