services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    working_dir: /app
    command: npm run dev
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - PORT=3001
    env_file:
      - ./backend/.env
    command: node dist/index.js

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: homeiq
      POSTGRES_PASSWORD: homeiqpassword
      POSTGRES_DB: homeiq
    ports:
      - "5432:5432"
