services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    # volumes:
    #  - ./backend:/app
    working_dir: /app
    command: node dist/index.js
    environment:
      - PORT=3001

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001

  db:
    image: postgres:15
    container_name: homeiq-db
    restart: always
    environment:
      POSTGRES_USER: homeiq
      POSTGRES_PASSWORD: homeiqpassword
      POSTGRES_DB: homeiq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
